perl grep.pl -count adventures
perl grep.pl -count airlock
perl grep.pl -count ancients
perl grep.pl -count army
perl grep.pl -count battleship
perl grep.pl -count chargen
perl grep.pl -count combat
perl grep.pl -count deck_plans
perl grep.pl -count deckplans
perl grep.pl -count drop_tank
perl grep.pl -count economy
perl grep.pl -count fleet
perl grep.pl -count hatch
perl grep.pl -count jump_shadow
perl grep.pl -count life_support
perl grep.pl -count marine
perl grep.pl -count megacorp
perl grep.pl -count merchant
perl grep.pl -count near_c
perl grep.pl -count piracy
perl grep.pl -count psionics
perl grep.pl -count robots
perl grep.pl -count scout
perl grep.pl -count ship_combat
perl grep.pl -count skills
perl grep.pl -count space_operation
perl grep.pl -count speculative_cargo
perl grep.pl -count squadron
perl grep.pl -count starport
perl grep.pl -count task_system
perl grep.pl -count vehicle
perl grep.pl -count vilani
perl grep.pl -count weapons
